
server:
   port: 9000

spring:
  cloud:
    gateway:
       routes:
       - id: loginMicroservice
         uri: http://login-service.default.gowthamshankar.net/
         predicates: 
         - Path=/ecommerce/login/**

       - id: orderMicroservice
         uri: http://order-service.default.gowthamshankar.net/
         predicates: 
         - Path=/ecommerce/order/**